$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'AniWatchTV-tvOS' do
  use_frameworks! :linkage => :static

  platform :tvos, '12.4'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes not yet available on tvOS
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # An abosolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  target 'AniWatchTV-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
