export * from './anime-details.interface';
export * from './anime-episodes.interface';
export * from './anime-list.interface';
export * from './anime-players.interface';
export * from './user.interface';
export * from './watch-list';
export * from './paginate';
export * from './anime'
export * from './resolve-player.dto'
export * from './player-response'
